name: openai_gym
channels:
  - conda-forge
dependencies:
  - python=3.9
  - click
  - jupyter
  - jedi
  - ipykernel
  - dill
  - pytest
  - pip
  - dill
  - nb_conda
  - pip:
    - jupyternotify
